### ISSUE TITLE
Game Crashed When I load larger file

### ISSUE THREAD

**Issue by jfglzs** [sakura-ryoko/litematica#19]
Crash Loading larger file
[17:44:48] [Render thread/INFO]: Loaded entity minecraft:wolf
[17:44:48] [CullThread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "blockPos" is null
[17:44:48] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.distSqr(CullTask.java:189)
[17:44:48] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.closerThan(CullTask.java:184)
[17:44:48] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullBlockEntities(CullTask.java:157)
[17:44:48] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:69)
[17:44:48] [CullThread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[17:44:50] [Render thread/ERROR]: Error saving option 亮度: DataResult.Error['Value 16.0 outside of range [0.0:1.0]']
[17:44:51] [Render thread/ERROR]: Error saving option 亮度: DataResult.Error['Value 16.0 outside of range [0.0:1.0]']
[17:44:58] [Render thread/INFO]: [CHAT] [17:44:58] [Creative] Chen_Linjie_DL joined Creative
[17:45:01] [Render thread/INFO]: [CHAT] [17:45:01] [Creative] Chen_Linjie_DL left Creative
[17:45:29] [Render thread/INFO]: LitematicaSchematic: executing Vanilla DataFixer for Tile Entities DataVersion 3465 -> 3953

**Comment by jfglzs** [comment]
[latest.log](https://github.com/user-attachments/files/16232795/latest.log)

**Comment by sakura-ryoko** [comment]
Based on the above input, can you try to reduce your mods such as with `dev.tr7zw.entityculling` and seeing if that helps.

**Comment by sakura-ryoko** [comment]
Basically to see which mod is causing the problem.
